#!/bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width            2
bspc config window_gap              5

bspc config split_ratio             0.52
bspc config top_padding		    27
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config single_monocle          true
bspc config focus_follows_pointer   true
bspc config focused_border_color    "#e60053"
bspc config pointer_modifier        mod1

bspc rule -a Screenkey manage=off
bspc rule -a mpv state=floating
bspc rule -a Firefox-esr desktop='^9'
bspc rule -a Transmission-gtk desktop='^8'
bspc rule -a st-256color:pmixer state=floating
bspc rule -a st-256color:nmtui state=floating

xsetroot -cursor_name left_ptr &
polybar top &
