#!/bin/sh
# Prajwal Gaonkar
# records screen using ffmpeg

# Records video in 1366x768 resolution and no audio is recorded
# Uses the ultrafast preset, so less CPU usage but larger filesize

FILE="screencast_$(date +%I_%M_%S)".mkv
notify-send "recording $FILE"
ffmpeg -video_size 1366x768 -framerate 30 -f x11grab -i :0 -c:v libx264 -preset ultrafast "$FILE"
notify-send "recording Terminated"
