#!/bin/sh
#screencapture using ffmpeg

#Records video in 1366x768 resolution and no audio is recorded
#Uses the ultrafast preset so not much CPU usage but large filesize
ffmpeg -video_size 1366x768 -framerate 30 -f x11grab -i :0.0 -c:v libx264 -preset ultrafast $1
