#!/bin/sh
# Prajwal Gaonkar
# This script is for setting wallpaper

# copy image to ~/.config/ directory
cp "$1" ~/.config/wal.png

# set wal.png from ~/.config/ dir as wallpaper 
xwallpaper --zoom ~/.config/wal.png
notify-send "$1 set as Wallpaper" -t 3000
