Player:
	Color: F20C67
Game:
	IntroductionPromptVersion: 1
	MouseScroll: Standard
Sound:
Graphics:
	UIScale: 1.5
	ViewportDistance: Far
Server:
Debug:
	UUID: 9085a8fe-8af1-41c1-af1c-36ffc45e5f4f
	SendSystemInformation: False
	SystemInformationVersionPrompt: 6
Keys:
