#!/bin/sh
# Prajwal Gaonkar
# mounts /dev/sdb1 and opens it in ranger file manager.
# upon quitting ranger unmounts and deletes mountpoint.

mkdir /home/prajwal/mnt
sudo mount /dev/sdb1 /home/prajwal/mnt
sudo st -e ranger /home/prajwal/mnt && sudo umount /home/prajwal/mnt
echo "unounting /dev/sdb1"
rm -r /home/prajwal/mount
